governance-game/governance-game

- AUTHORS.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- CREDITS.md
- LICENSE.md
- README.md
basic setup of files
-----
[View rendered AUTHORS.md](https://github.com/Ainali/governance-game/blob/master/AUTHORS.md)
[View rendered CODE_OF_CONDUCT.md](https://github.com/Ainali/governance-game/blob/master/CODE_OF_CONDUCT.md)
[View rendered CONTRIBUTING.md](https://github.com/Ainali/governance-game/blob/master/CONTRIBUTING.md)
[View rendered CREDITS.md](https://github.com/Ainali/governance-game/blob/master/CREDITS.md)
[View rendered LICENSE.md](https://github.com/Ainali/governance-game/blob/master/LICENSE.md)
[View rendered README.md](https://github.com/Ainali/governance-game/blob/master/README.md)
> Initial commit

- cards/introduction.md
Fixes #11 and #14 (at least for now, some more might be done in the future)
-----
[View rendered cards/introduction.md](https://github.com/publiccodenet/governance-game/blob/add-introduction/cards/introduction.md)
> Adding introduction card

- CONTRIBUTING.md
Fixes #32
-----
[View rendered CONTRIBUTING.md](https://github.com/publiccodenet/governance-game/blob/documenting-card-addtion/CONTRIBUTING.md)
> Add details for how to add a new card

- Makefile
- cards/rules-about.tex
This card gives a brief introduction to the Foundation for Public Code.
Fixes #38
> Add an About card

- CONTRIBUTING.md
- PRINTING.md
Fixes #40
-----
[View rendered CONTRIBUTING.md](https://github.com/publiccodenet/governance-game/blob/printing-documentation/CONTRIBUTING.md)
[View rendered PRINTING.md](https://github.com/publiccodenet/governance-game/blob/printing-documentation/PRINTING.md)
> Documenting printing process

- README.md
fixes #37
Co-authored-by: @Ainali 
-----
[View rendered README.md](https://github.com/publiccodenet/governance-game/blob/doc-need-font-inter/README.md)
> Document need for Inter fonts for png generation

- README.md
Co-authored-by: @Ainali 
-----
[View rendered README.md](https://github.com/publiccodenet/governance-game/blob/roadmap-1.0/README.md)
> update roadmap for 1.0.0

- Makefile
- cards/actor-commissioning-public-organization-2.tex
- cards/actor-development-vendor-2.tex
- cards/actor-inhouse-developer-2.tex
- cards/actor-replicating-public-organization-2.tex
- cards/actor-replicating-public-organization-3.tex
partially addresses #36 but does not add "stewardship organization"
> Create some duplicate cards

- RELEASING.md
Co-Authored-By: Eric Herman <eric@publiccode.net>
-----
[View rendered RELEASING.md](https://github.com/publiccodenet/governance-game/blob/release-guide/RELEASING.md)
> Add guide for releasing a new version of the game

- CODE_OF_CONDUCT.md
null
-----
[View rendered CODE_OF_CONDUCT.md](https://github.com/publiccodenet/governance-game/blob/cc0-coc/CODE_OF_CONDUCT.md)
> Convert to CC0 code of conduct

- PRINTING.md
null
-----
[View rendered PRINTING.md](https://github.com/publiccodenet/governance-game/blob/kerning-was-fixed/PRINTING.md)
> Issue #37 was resolved

- CONTRIBUTING.md
- CREDITS.md
- README.md
null
-----
[View rendered CONTRIBUTING.md](https://github.com/publiccodenet/governance-game/blob/markdown-tidy/CONTRIBUTING.md)
[View rendered CREDITS.md](https://github.com/publiccodenet/governance-game/blob/markdown-tidy/CREDITS.md)
[View rendered README.md](https://github.com/publiccodenet/governance-game/blob/markdown-tidy/README.md)
> Markdown tidy

- CONTRIBUTING.md
null
-----
[View rendered CONTRIBUTING.md](https://github.com/publiccodenet/governance-game/blob/rel-links/CONTRIBUTING.md)
> Make links relative, explictly name files we want someone to edit

- README.md
null
-----
[View rendered README.md](https://github.com/publiccodenet/governance-game/blob/fix-tags-link/README.md)
> Fix tags link

- script/release-body.sh
We only want to automatically create releases for tags which follow our release process, otherwise we should error.
> Error unless start of CHANGELOG matches VERSION

- README.md
Interactive is already implied by it being a game.
We already made the first point in the roadmap, so remove this.
> Remove "interactive" and update roadmap

- .github/workflows/release-on-tag.yml
Co-authored-by: Jan Ainali <jan@publiccode.net>
> Game is not in pre-release

- GOVERNANCE.md
Based on the Standard governance.
Fixes #89
> Add GOVERNANCE file

- CONTRIBUTING.md
- SECURITY.md
Aims to meet two requirements in the Standard for Public Code.
> Add SECURITY.md

- SECURITY.md
They're already vulnerable, but perhaps less so.
> s/vulnerable/more vulnerable/

- CONTRIBUTING.md
> Add "0. Expectations" section before making changes

- Makefile
can test with `touch clean` before a  `make clean` before and after the patch
> Add remaining (and fix) .PHONY target labels

- Makefile
- cards/scenario-own-scenario.tex
- cards/starting-state-5.tex
- cards/starting-state-8.tex
Remove starting state card 5 to make room. Former starting state card 8 becomes new number 5.
Fixes #54
> Add scenario for own situation

- Makefile
- script/check-one-page.sh
- script/check-pdf-for-each-tex.sh
- script/number-pdfs.sh
Because I moved the "make view-foo" targets down, the diff is a bit noisy.
> Extract scripts from Makefile, clean-up, document

- Makefile
- box/printers-studio-box.svg
fixes #113
Co-authored by: @ericherman
> Add version number to box

- standard-for-public-code-assessment.md
> Pass for catalog

- README.md
Will at least help me not to be confused the next time I need to update it.
> Add basic information about the website

- index.md
> Add link to workshop page on About

- assets/object-back.svg
> Change color on object cards backside

- standard-for-public-code-assessment.html
With bcd1b4e76dca15b5b6ff8e8e5f4346c872d94f5f it now meets the requirement about grouping commits.
> Update standard assessment

- CONTRIBUTING.md
(without changing the font size)
> Style: text must fit on one card

- README.md
Adding levels to roadmap to make it clear it is on the long term.
> Add multiple target groups to README

- README.md
https://github.com/publiccodenet/governance-game/issues/63
> Add home printing process to Roadmap, issue #63

- Makefile
> put object cards in numerical order

- .github/workflows/check-on-push.yml
- .github/workflows/release-on-tag.yml
https://github.com/actions/checkout/blob/main/CHANGELOG.md
> Update github actions/checkout from v2 to v4

- index.md
Partly addresses #163
(separate from #164 that addresses the README)
> Fix video link in index.md
